### ISSUE TITLE
Translate Terms & Conditions + Privacy pages

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#189]
Create 2 separate pages, one for `/terms` and another for the `/privacy`. We can use as the template text the ones in: https://github.com/vocdoni/vocdoni-ui/tree/main/components/pages/policy and adapt the necessary parts to adapt to the UI-Scaffold. 

Tasks:
- [x] Create the "Terms" page
- [x] Create the "Privacy" page
- [x] Import all the texts 
- [x] Format texts and add to the translations files
- [x] Adapt the text changing the needed words

**Comment by elboletaire** [comment]
Not closing to keep record of translations

**Comment by elboletaire** [comment]
Reopened since the PR (which wasn't related btw) is not yet merged #849
