### ISSUE TITLE
Bug: Vote overwrite + anon

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#275]
1 - If a voting process is created without checking the "Vote overwrite" option, when voting, the UI shows the "Re-submit your vote" button, when it shouldn't appear. 

2 - On top of this, if you refresh the page, the "Vote" button also appears, instead of showing "You already voted " or a similar text. 

For doing this second part, maybe we should store some info (processId?) in the localStorage to check if the user has voted, or capture the "500 Error Overwrite count reached" and display it in a better way, instead of a big error, a informative text explaining you already voted with this account? Let's discuss it.

**Comment by elboletaire** [comment]
Superseeded by https://github.com/vocdoni/ui-components/issues/108
