### ISSUE TITLE
Integrate the "Faucet" into the ui-scaffold

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#278]
As Vocdoni we want to have a unified flow inside the UI-scaffold to facilitate the user-flow of requesting tokens. To do so, we will move the "faucet" inside the UI-scaffold:

1 - Having a page dedicated to the faucet, in "/faucet" with the current flow
2 - Create a component to integrate a popup in the "Create Election" flow, and be able to display the faucet and request tokens in the same flow, taking into account that in that step, the organizer is has the wallet connected and only needs to do the 2nd part of the flow (sign with the social account), receive the tokens and update it in the UI.

**Comment by nigeon** [comment]
https://github.com/vocdoni/ui-scaffold/pull/302

**Comment by elboletaire** [comment]
closed by #302
