### ISSUE TITLE
Pre-fetch the anonymous info to reduce the wait time for the voter

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#289]
With the anonymous voting feature, it comes with new circuits and libraries to download, making the voting flow slower, as the browser needs to download files with more size. We can try to start the pre-fetch once the user is logged, to reduce the waiting time for the voter, instead of doing when the user is about to vote.

- [x] Add the pre-fetch function when the user is correctly logged and is part of the census.

**Comment by nigeon** [comment]
Is this one still blocked by the X task?

**Comment by jpaulet** [comment]
Edited the task. No, now it shouldn't be blocked by any issue. Only check if the the election is an "anonymous" one, and start pre-fetching all the needed libraries when the page render is finished.
