### ISSUE TITLE
"Org Creation" page revamp

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#315]
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e4cb6552-5d6f-42b5-a7d0-3ba23114228e)

Tasks:
- Adapt the design
- Change "Check" step to "Organization"
- Delete the "accepts markdown" text
- Add new translations
- Add the icons

**Comment by elboletaire** [comment]
closed by #319
