### ISSUE TITLE
Problems with "next" button in Process Create form

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#322]
- It's not visible on small screens.
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/8f57f8f7-b677-4679-8578-2a78168d5c02)
- It does not have disabled styles, and it's disabled most of the time.
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/39ebb12b-5591-4a28-830e-4b52f0e266c0)

Tasks: 
- [ ] Make sure the "Next" button is always near the content, and if the content is not too long, visible inside the screen.

**Comment by jpaulet** [comment]
True, thanks for the feedbak. Preparing the "disabled" state of the button. We'll use this issue to improve the button, the button visualization and the states.
