### ISSUE TITLE
Dynamically retrieve faucet amount (and remove env `FAUCET_AMOUNT`)

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#393]
Right now we have an env var `FAUCET_AMOUNT` that defines the **texts** of the amount of the faucet given (it has no actual functionality in the faucet itself).

This data can now be retrieved via the faucet API, and should be replaced everywhere to be dynamically fetched.

**Comment by jpaulet** [comment]
@elboletaire can we close this one?

**Comment by elboletaire** [comment]
Yes
