### ISSUE TITLE
onvote review

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#440]
- [x] english translation broken for relative time in process view
- [x] disable all languages but english
- [x] during the vote of an anonymous election, show a text over the vote button describing it can take quite long.
- [x] some components have been repeated only for slight changes (Navbar only changes the logo, no need for a new component for that)
- [x] the blue dotted background in the landing page should be blurred
- [x] review typography in all project and ensure they match with the design
- [x] vote button has a hover status when disabled and loading
- [x] in secret processes, the results tab should not extend the entire width. It should have the same max-width as the questions tab.
- [x] in process view, borders and shadows of questions do not match the design
- [x] in process view, when changing from questions to results, the footer moves up and down, even the height is apparently the same (I can't reproduce it)
- [x] in process create, increase max census size slider contrast
- [x] in process create, highlight the total cost of the election
- [ ] Actions tooltips take too much time to show up. Consider using chakra tooltips.
- [x] "World wide voting" text in sidebar overlaps content in small screens (i.e. iPhone 11). See ref1
- [x] Voteid overflows on small screens (i.e. iPhone 11). See ref1
- [x] Fix topbar with different attributes (see ref2 in post below)
- [x] Replace also the update the terms and privacy pages in the drop-down menu. (see ref3)
- [x] In huge screens (2k/4k) the width shouldn't be full width (see ref4)
- [ ] Update the social media card for Onvote.app with the correct information.
- [ ] Relative dates appear in catalan

ref1
![ref1](https://github.com/vocdoni/ui-scaffold/assets/153305/d5f6ac84-d706-4f2b-aef0-b5620a6fbb9f)
ref4
![ref4](https://github.com/vocdoni/ui-scaffold/assets/153305/9c2c20b9-70a6-4843-b421-30e1195ac149)

Please edit the list yourself if you find or fix issues.

**Comment by ferranrego** [comment]
**Ref3.**

Replace the update the terms and privacy pages in the drop-down menu.
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/09e6c8fb-ffb6-4684-9c8c-671bf7ab3e40)

**Comment by gerouvi** [comment]
Ref2 


https://github.com/vocdoni/ui-scaffold/assets/78085338/a5c8dfa7-666e-4ef5-a811-d0e4703f35cd

Sorry, I don't understand the issue. If you're on the home page and open process create, when you close it, you return to the home page. If you do it from 'my org,' you return to my org

**Comment by ferranrego** [comment]
**Ref5**

We should update the social media card for Onvote.app with the correct information.
- **Title**: Onvote - Anonymous, modular and gassless voting for Web3
- **Description**: The ultimate Web3 voting platform. Experience anonymous, flexible, verifiable and gasless digital voting within a zero-config UI.
 
- **Image**:
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/776fd27a-bc34-4c5c-a3a6-fe597dd46100)
