### ISSUE TITLE
[vocdoni.app] Solve visual errors 

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#484]
- [x] Footer: remove text-underline in links, make font color black
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/ce5e9df9-fdcc-40fb-b0db-5d65e94ec5ad)

- [x] Solve visualization of the cards in the landing:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/c036cdfd-b1ec-4c7a-8681-9748d105dfc2)

- [x] Solve page layout in the creation steps: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/0b1a25c9-05fa-4adc-8f3b-b1859067ead0)

- [x] In the creation options, the checkbox is now visible:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/d1f3c054-b369-44dc-b076-8f4a156e10c5)

- [x] Some images are not visible: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e10e0d8b-5cdb-4b71-90d1-5e54ff9ddf00)

- [x] The steps visualization is not correct:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/0451228d-b465-4dc4-92d8-c9e722f57c88)

- [x] The "back" button in the voting page is not correct:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e9b18656-4e36-4178-92a8-fa5c6fb617ef)

**Comment by elboletaire** [comment]
reviewed, all done
