### ISSUE TITLE
[ onvote app ] Solve visual issues

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#485]
- [x] Add more margin between the section and the title
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/f7d88b48-fef7-432e-b2f4-e87894834077)

- [x] The github icon is blue, move to white
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/058719e1-1543-4ad9-8ea0-d21070a70e78)

- [x] Add more paddding to the modals
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/f647b134-1cab-429b-9ca4-c1ad2d9c32c0)

- [x] Give more space between the "close form" icon and text  
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/b8d6a954-52c0-48b6-b27b-f9eda0c189b1)

**Comment by elboletaire** [comment]
all done here too, closing. I opened a new issue to track something I found (#495), but all in this issue is done already.
