### ISSUE TITLE
mobile responsive issues

### ISSUE THREAD

**Issue by gerouvi** [vocdoni/ui-scaffold#512]
All views
- adjust views padding

Process
- Adjust font-size in the title (reduce to 32px) + add at least 10px of margin-top
- Reduce the aside size, align the content by rows instead of columns, make the text smaller
- Make the "parameters list" (End date, Census Type, Created by...) smaller and align it horizontally
- The questions and options don't expand to 100% of the availabe width, looking weird
- Align all the footer content to the center
- Remove checkbox / radio in mobile

**Comment by elboletaire** [comment]
Just to confirm. The website now is bigger than it was before. It had a max-size of around 1760px and now is 1800px (which looks more like a proper width definition, but I have to ask anyway....), is this correct @gerouvi?
