### ISSUE TITLE
Add "custom plan" features in the creation form

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#530]
As Vocdoni, we want to add all the features that the protocol supports but the UI don't support in a "self-service" mode, only in custom project mode. 

When clicking one of those options, a popup will appear that will let the user to send a email or schedule a call.

- [x] Customization
- [x] Voting types
- [x] Census types
- [x] Contact us button
- [x] Contact us popup form with schedule option

Visual References and copies:

- Customization
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/af09cf8b-388e-4ec5-a960-2ad17b3c255c)

- Voting types
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e2879cf4-f3f4-44dc-a1aa-5d3cc6a52886)

- Census types
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/ec83514a-d070-42f1-8f76-73258e13d166)

Note that we need to increase the separation between the cards in the grid (margin: 15px) and center all the content. 
Also, when selecting a census type, we have to hide all the cards and show the census itself, with a "Back" button on top.

- Contact us button (looks like text, but it's a button)
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/51b59162-1151-42bf-98c8-651dbb0fdc54)

- Contact us popup form with schedule option
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/4dff855a-8996-4392-be35-36994dc7b91c)

The "Book now" button, is an integration with a external calendar:

`Button code
<link href="https://calendar.google.com/calendar/scheduling-button-script.css" rel="stylesheet">
<script src="https://calendar.google.com/calendar/scheduling-button-script.js" async></script>
<script>
(function() {
  var target = document.currentScript;
  window.addEventListener('load', function() {
    calendar.schedulingButton.load({
      url: 'https://calendar.google.com/calendar/appointments/schedules/AcZssZ29VUbJIqlHtdY32eVUd2OhbjfQLoiHhTAk34Ct6PianaFnwediCb6K021zcX5RaKDdd76eZS-O?gv=true',
      color: '#3F51B5',
      label: 'Book an appointment',
      target,
    });
  });
})();
</script>
`

But we can create it with Chakra for having translations and more options.

**Comment by elboletaire** [comment]
Closed by #555
