### ISSUE TITLE
Lost translations

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#538]
In catalan at least
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/a557fea5-ab52-4609-bb03-c1ec80c1dbd9)

**Comment by elboletaire** [comment]
Actually, these aren't lost... I think we decided to leave them this way when we added the "anonymous magic is happening" message, since translating such message to spanish and catalan may be weird. @jpaulet how should we translate it? The submitting part is easy, I'm wondering what to do with this one:

> Please wait while the anonymous magic 🪄 happens.
> This can take up to several minutes; don't close the window.

**Comment by jpaulet** [comment]
We should address this more as a whole.. bc right now we are only fully supporting ENG and some ESP & CA translations are missing or not appropriate. I will create a new issue to deal with this.

**Comment by jpaulet** [comment]
Added all the missing translations in the "landing app" page. Closing this as we will merge them with this issue.
