### ISSUE TITLE
To improve the Open Graph preview on social media for Vocdoni.app and Onvote.app

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/ui-scaffold#540]
**Proposal:**
To enhance the Open Graph previews for Vocdoni.app and Onvote.app on social media.
The idea is to display the actual content of each specific page—be it an organization profile, a voting page, or the homepage—complete with a relevant logo (e.g. Vocdoni or Onvote for the main page, and the organization's logo for others), the page title, and a brief description.

Also, we should make sure that the images appear properly fitted in the preview.

**Reason:**
This tweak could significantly boost our social media engagement and give our posts a more polished, professional look.

**This is how it looks on different social media:**
**Onvote.app**
- **Twitter**
Shows generic information about Onvote when it must show information about the process/org. No images.
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/691a1241-d50e-48d5-b3bc-c5d665aaed34)
- **Warpcast**
Wrong info and generic (It shows info about Vocdoni.app).
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/01587f37-cc89-4427-9746-38c62d235e02)
- **Telegram**
Shows generic information about Onvote when it must show information about the process/org.
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/3976ac1b-151e-43d4-8b52-34cf742f6276)

**Vocdoni.app**
- **Twitter**
It doesn't work. Doesn't bring any preview.
- **Warpcast**
It creates a preview that only shows generic information.
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/9a30b33e-4d76-46e9-bc69-ea2508093877)
- **Telegram**
It creates a preview that only shows generic information.
![image](https://github.com/vocdoni/ui-scaffold/assets/3515290/b2e6eab0-004f-49d3-a8a1-a7ad6711e4ce)

**Comment by ferranrego** [comment]
Could we prioritize this issue for the next Sprint?

cc/ @jpaulet

**Comment by jpaulet** [comment]
> Could we prioritize this issue for the next Sprint?
> 
> cc/ @jpaulet

We started by improving the metatags, adding new ones (telegram, whatsapp, linkedin, etc) and improving the copies. 

What you are asking (dynamic tags depending on the content) right now is not possible, as we serve static pages. We should do a discovery session to explore the best solution to deal with it.

**Comment by jpaulet** [comment]
Related: https://github.com/vocdoni/ui-scaffold/issues/613

Closing it and discussing it in the next Tech Weekly to find a possible (less "invasive") solution.
