### ISSUE TITLE
Stream visualization on mobile devices looks like a wrongly positioned ad

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#564]
I'm not sure we should be showing it like this for mobile phones. I'd remove the sticky logic for mobile devices tbh.
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/24af2e37-b020-4d37-8afd-d61169f4e552)

**Comment by jpaulet** [comment]
With mobile the streaming should be fixed

**Comment by elboletaire** [comment]
> With mobile the streaming should be fixed

We should then position it beetter, since its current positioning doesn't seem correct for mobile phones 😕
