### ISSUE TITLE
When creating processes, prompt for confirmation in different scenarios

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#59]
This is a follow-up of #56. When doing that, we realized that it was interesting to prompt for confirmation in different scenarios, but most of them have complications or can't be done. 

This issue is as a reminder of this, with all the information of each type of prompt, in case we can investigate it further in the future:

- confirm when trying to leave the page: using react-router v6 implies creating a custom router and a custom history (and needs more investigation, since there's nothing documented related to v6 stable).
- confirm when changing between census types: ignored for now since it's not problematic to change tabs, and should be handled by a better UX on that step.
- confirm when changing wallet accounts: this can't be done, since there's no way to avoid a user from changing their account on metamask (nor any web3 provider). The only controllable behavior is the `on account change` event (which happens after the account is changed, making it useless for this case).

**Comment by jpaulet** [comment]
@elboletaire what we should do with this issue? Closing it or creating a specific one to solve this issue?

**Comment by elboletaire** [comment]
None of the tasks of this issue were done, so I'd say leave it open until we can dedicate some time and do any of the prompts.

**Comment by elboletaire** [comment]
Actually... should we lose time with this? All are edge cases...

**Comment by jpaulet** [comment]
Task closed. If we encounter any issues in the future, we'll take care of them, but we won't dedicate time to minor or uncommon scenarios.
