### ISSUE TITLE
Onvote landing

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#592]
We have to improve our onvote landing page:

ToDo:
- [x] Change all the "vocdoni app" references to "onvote" 
- [x] Remove the "Roadmap" section
- [x] In the hero section, give more horitzontal space between the 3 columns
- [x] Add a new section called "Web3 Governance"

![Screenshot 2024-03-14 at 13-10-13 uizard](https://github.com/vocdoni/ui-scaffold/assets/6894329/f114f559-6d78-4af3-b5cc-b5e7c06f5fc1)

Ref: https://app.uizard.io/p/3b6ad3a6/preview

**Comment by selankon** [comment]
Links

onvote -> create process
farcaster -> farcaster.vote
plugin aragon -> app.aragon.org
contact us -> 'info@vocdoni.org'
