### ISSUE TITLE
"Sign first" button is shown when election is end

### ISSUE THREAD

**Issue by selankon** [vocdoni/ui-scaffold#601]
![image](https://github.com/vocdoni/ui-scaffold/assets/16777076/507e6269-9ac3-4e80-939c-795ba88e6164)

Vote is end but the button is shown :(

**Comment by selankon** [comment]
It seem that `isAbleToVote` is true, and should not.

https://github.com/vocdoni/ui-scaffold/blob/1bf340d18e57277509be894a30a113c3b72d0f31/src/components/Process/Aside.tsx#L197-L203

This comes from  `@vocdoni/react-providers`

**Comment by selankon** [comment]
btw seems related to https://github.com/vocdoni/ui-scaffold/issues/587

**Comment by elboletaire** [comment]
Hey this is not an issue. You need to sign in order for us to know if you have voted or not. If you have not voted, nothing should be shown, but if you voted, your vote id should be shown in there... and for that we need to sign.

> btw seems related to #587

Yes, that's the real issue. Closing this.
