### ISSUE TITLE
Change header metadata dinamically

### ISSUE THREAD

**Issue by selankon** [vocdoni/ui-scaffold#613]
Some of the header metadata information can be updated dinamically, for example, adding the title of the election and updating the OpenGraph tags. 

However this can only be achieved dinamically on the client side rendering, here few methods i found googling a bit:

- Using [React Helmet](https://www.npmjs.com/package/react-helmet) package
- Using a [useEffect](https://www.30secondsofcode.org/react/s/use-title/) and modifying the document object.

This, will have a nice effect on a Javascript enabled client side. But won't have any effect on the OpenGraph preview cards, since the crawlers don't use Javascript. To acquire this **SSR is needed**, see [this discussion](https://github.com/nfl/react-helmet/issues/213).

**Comment by selankon** [comment]
Some solutions the people propose on the above discussion are:

- Check user agent to [serve a specific header](https://github.com/nfl/react-helmet/issues/213#issuecomment-725235820) if the GET call comes from a bot.
- Using [react static](https://github.com/nfl/react-helmet/issues/213#issuecomment-421183794) for SSR rendering 

This solutions are not good enough for me atm, so I suggest to research a little bit more

**Comment by selankon** [comment]
This read seems to be what we need:

https://web.dev/articles/rendering-on-the-web

Other things I found that can help:

https://prerender.io/ 
https://github.com/stereobooster/react-snap

**Comment by selankon** [comment]
It seems from now the best solution is 

https://vite-plugin-ssr.com/vike

**Comment by elboletaire** [comment]
The only way is via SSR, and right now is more than discarded.

As you just commented, the best solution would be to use vike, given our current tech stack.

Closing since there's no intention to change ui-scaffold from static pages to a SSR version.
