### ISSUE TITLE
Visual Improvements 

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#661]
We should address the following visual improvements:

- [x] Improve OR/AND selector in the "Gitcoin Passport" census type. Change the current switch to the "custom radio button" Chakra component, while preserving the text change depending on the selected option: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/c2d9a730-1c3c-48ad-b03d-762f951fee5b)
- [x] In the "Gitcoin passport" census, once selected add in the end of the description the following text "Read more about Gitcoin's Scorer & Thresholds here" with a link in the "here" that opens a new tab linking: "https://docs.passport.gitcoin.co/building-with-passport/major-concepts/scoring-thresholds"
- [x] The minimum possible GPS should be "1" instead of "0" (both for the numeric input & slider). 
- [x] The default GPS should be set to "20".
- [x] Correct the typo: `sybyl-attack` to `sybil-attack`.
- [x] In the "Token census", the description is as follows: "Configure the census by choosing a token from any available network. You can request a token here." but the "here" is not a link. Add the link to the "Add token form" (https://tally.so/r/mO46VY).
- [x] Change the text of the modal:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/78e53d1b-9d9c-4644-8973-8fb029e81e03)
By removing: "Option not available in the free plan. To use it, you need to purchase the custom project plan." and replacing by: "XXXX is a Premium feature". (for instance: `Customization is a Premium Feature` or `SMS-based census is a Premium Feature`). 
Also, change the "Or you can directly schedule one quick call (30'') with our experts to help you create your desired voting project." to "Schedule a 30-minute call with our team to discuss your voting project. We'll guide you through the process and tailor solutions to meet your specific needs."
Same text for Spanish and Catalan.
- [x] Remove top margin space from the "Verify your vote" box and add some bottom margin.
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/20a9927f-f2c2-4cc3-a373-f7fec855671d)
- [x] Change "You can correct your vote only once." to "You can correct your vote once."
- [x] Add the "magic" emoji in the phrase: "Please wait while the anonymous magic happens  🪄."
- [x] When click in the "Request Custom Tokens", the form is open but also the option is selected in the dropdown. Prevent the dropdown to show this as an option: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/90bf2d5e-d8f8-4906-babe-fae18fbca23f)
- [x] The "pro" label in the census is not shown correctly (onvote theme): 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e10dc588-52aa-4a9a-9914-ea9bcdfe8e53)
- [x] Add spacing between the title and the description of the "voting types" & "other settings" cards: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/63206f50-ad70-4e1d-a8db-796f48ae65ee)
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/ed03ee51-251c-419e-b4ac-b87a41765081)

**Comment by selankon** [comment]
ftr about pro census have to be shown like this 

![image](https://github.com/vocdoni/ui-scaffold/assets/16777076/ceb0329a-1689-4b3a-a1e8-84924523afd7)
