### ISSUE TITLE
Private Org Dashboard

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#686]
As organizer, I want to have a private voting dashboard where I can quickly view all my voting projects, stats, control the voting flows, settings and review my expenses. 

Implement an admin dashboard, so that organizers can quickly review all entity data, access the list of created processes, and view the data of the organization through a private area, accessible only by logged-in admins.

**Pages & To-Do:**

- [x] #687
       -  The dashboard should display an overview of key metrics and data related to the organization.
       -  Metrics might include active processes, total voters, recent activity, and any critical alerts or notifications.

- [x] #688
        A dedicated page listing all created processes.
        Each process should display key details such as status, creation date, and any important notes.
        Option to view more detailed information about each process by clicking on it.
        
- [x] #689
        A detailed page for each process, accessible from the Processes page.
        This page should display comprehensive information about the selected process, including:

        -     Process name and description.
        -     Current status and history of status changes.
        -     Dates (creation, start, end).
        -     Participants and their status (e.g., voted, pending).
        -     Questions & results.
        -     Any associated files or documents.
        -     Buttons to change the process status (Start / Pause / End / Cancel).

- [x] #690
        A page displaying detailed data about the organization (entity).
        Information should include organization name, contact details, description, and any relevant statistics.
        Option to edit organizational details if necessary.

- [x] #691
        A sidebar should be present for easy navigation between the Dashboard, Processes, and Entity pages.
        The sidebar should be collapsible for a better user experience on different screen sizes.

**General**:

- [x] Reuse the header to accommodate in the existing designs.
- [x] Use the current components and adapt the design when necessary.
- [x] Make sure that in each app, the styles are correct and responsive.
- [x] Test all the features
- [x] Admin Access Control: Ensure the admin dashboard is only accessible by logged-in admins.Redirect non-admin users attempting to access the dashboard to a login page.

**Designs**:

![my_entity_empty](https://github.com/vocdoni/ui-scaffold/assets/6894329/86834cac-35f9-4c6c-945c-55d833cba202)
![my_entity](https://github.com/vocdoni/ui-scaffold/assets/6894329/251ec9c5-fab9-4ff8-855a-7b826ffa2221)
![dashboard_empty](https://github.com/vocdoni/ui-scaffold/assets/6894329/8abaf811-b940-4274-8aa8-5d045c22a8d6)
![dashboard](https://github.com/vocdoni/ui-scaffold/assets/6894329/f7e75fae-43e2-41d4-92d1-ac20fe24d061)
![voting_with_status_buttons](https://github.com/vocdoni/ui-scaffold/assets/6894329/e2024b0b-d698-4188-99cf-97f8859ea9c1)
![voting_loading](https://github.com/vocdoni/ui-scaffold/assets/6894329/76523025-dc01-44bf-840f-9085aa25aed5)
![vote_details_upcoming](https://github.com/vocdoni/ui-scaffold/assets/6894329/26fe647b-2600-4482-a6d7-229bbd761fb3)
![vote_details](https://github.com/vocdoni/ui-scaffold/assets/6894329/3cbc28b4-9cac-4a57-903f-a4656fa17b82)
![voting](https://github.com/vocdoni/ui-scaffold/assets/6894329/7e063714-75c4-4b48-a339-6440745ce3c1)

**Comment by elboletaire** [comment]
Closed by a1115bfb3ca0e650dd900f4a9ff857176dc54132
